language: php
php:
  - 5.3

branches:
  only:
    - master
    - staging
    - release

notifications:
  email:
    recipients:
      - build@barrett.io
    on_success: always
    on_failure: always

env:
  global:
    # PAGODABOX_USERNAME
    - secure: "SF5G0yloZyVRzzcpCy3ouWkaBY+2FdfrZwK5QL849SUON4eKxvKlZuruF97C\n04t3UNh5oFo56mR9RuwfFaZ8BDapgKoFspb3fGD4xnjb2Odxud3tYsM24uvl\nLOrq28pZS/caN/GDNyzIckr4qjRMyXn7ydFBMXbtY//qHJxg0Lk="
    # PAGODABOX_PASSWORD
    - secure: "guIahVAckUv7VlmjBY8EpG1T+kQS8Wj8b0uS1PKrld3SD25DsRWdkAifzJs/\nSHVUh7LcqRnnZjR1nfiXKZHj/abKayYjpGv+3FM9w4xSz5QNvHihcifQwc6x\nL1BhBqeWTBbdnxiHUyXRwTh/rn/w4R1yI8+KkTvmh55UJ8ehgGU="
    # PAGODABOX_APP Targets
    - PAGODABOX_STAGING=staging-kdrcornell-com
    - PAGODABOX_RELEASE=kdrcornell-com

before_script:
  - ./scripts/prereqs.sh
  - phing ci-setup

script:
  ### TESTS ###
  - phing verify-pagoda
  - phing verify-kohana
  - phing test
  ### DEPLOYMENT ###
  - phing ci-deploy
