language: php
php:
  - 5.3

branches:
  only:
    - master
    - staging
    - release

notifications:
  email:
    recipients:
      - build@barrett.io
    on_success: always
    on_failure: always

env:
  global:
    # PAGODABOX_USERNAME
    - secure: "cT3JGi1zzGAp6LfUGygAblfm8A3PEy6QAwsuxOclDJcFQtcZnYX4sl/mO6ug\nhddru1+Cv5GGJL506j1uNbVlRcX3CY5RdZVOjG9QfDr+h7HV8DgaUHUzO68O\n3LP3HDsQsgDOrwUOqvcoNbMwdBmQsJ6TeUd2EmYCBWhbppXo/PQ="
    # PAGODABOX_PASSWORD
    - secure: "UshPi5d9ozn/1ic9iHftQHJl5z6NOKCHGwcwdR3v7cKZTugFXChE0EhKqARh\nEMzE4ogc/sz2WeQFSrkQLL7W7JpAQ3yahW7nO8PetzPhSAnmvt74/h/3SQlI\nljnC7iDyqF48kTquj+M2pA21Mteevqpe+ZFANCM/gTelMYWT+T8="
    # PAGODABOX_APP Options
    - PAGODABOX_STAGING=staging-kdrcornell-com
    - PAGODABOX_PROD=kdrcornell-com

before_script:
  - ./scripts/prereqs.sh
  - phing ci-setup

script:
  ### TESTS ###
  - phing verify-pagoda
  - phing verify-kohana
  - phing test
  ### DEPLOYMENT ###
  - phing ci-deploy
