<h2>History</h2>
<p class="big grey">A brief history of the beta chapter</p>
<hr />

<div class="row">
	<div class="span12 copy">
		<p>In 1905, ten undergraduates at Middlebury College realized that the social organizations available there were lacking in the strong ties between members that were the basis for the earliest fraternities.  These ten fellows, all members of the Commons Club, a loose-knit social organization at Middlebury, met at 14 Old Painter Hall and decided to create a new fraternity dedicated to the ideals of truth, justice, and virtue.</p>
		<p>Our founders wanted to develop an atmosphere that was nurturing of excellent moral character, dignity, gentlemanly conduct, and leadership as well as academic success and the strong ties of brotherhood that brought them together.  The result was Kappa Delta Rho.</p>
		<p>A few years later, a Middlebury graduate named Harold A. Severy came to Cornell University to pursue graduate studies, and brought &Kappa;&Delta;&Rho; with him.  On May 24, 1913, twenty-three men formed the Beta Chapter of Kappa Delta Rho here at Cornell.  During the twenties and thirties our house continued to grow. WWII, however, forced us to close our doors; &Kappa;&Delta;&Rho; lost seventy brothers to the war.  In the early fifties, local alumni recruited new members and this chapter reopened.</p>
		<p>In 1952, the House Committee of the recently re-chartered Beta Chapter of Kappa Delta Rho purchased the house and grounds at 312 Highland Road, a place with an extensive history of its own:  in 1908, Professor Jermiah Jenks leased the land to build a house.  The house, designed by Cornell Architecture students, was a marvel of the day because of its solid cement construction.  After several transactions, the house came into the possession of Claude Smith, of the family that built Ithaca Gun, the leading industry of the day.  Smith allegedly killed his wife in the house, and her ghost supposedly haunts Room 4 on stormy nights.  Claude's heir, Helen Brock Smith, came into the house in 1931.  She rented the house to Sigma Alpha Mu Fraternity, who then bought the land in 1938.  Sigma Alpha Mu let go of the house when they closed for WWII, and, after another owner, &Kappa;&Delta;&Rho; purchased the land on June 30, 1952.</p>
		<p>In 1956, Beta spearheaded a national interfraternity anti-discrimination drive, and we were the first chapter of a traditionally white fraternity to impledge an African-American.  We continue this philosophy of nondiscrimination to this day, as evidenced in 1992 when we became the first fraternity on the Hill to add a nondiscriminatory clause to its constitution.  This clause states that &Kappa;&Delta;&Rho; does not consider a candidate's race, religion, income, disability, course of study, or sexual orientation when considering him for membership.</p>
		<p>The most notable change in the house since &Kappa;&Delta;&Rho; took over was the addition of the new wing in 1967.  The addition more than doubled the capacity of the house and met the needs of the growing brotherhood. The house at 312 Highland Road has served as home to hundreds of brothers and will be home for hundreds more.</p>
		<p>For more information on the current Chapter, please visit our <a href="<?php echo URL::site('about'); ?>">About &Kappa;&Delta;&Rho;</a> page.</p>
	</div>
</div